Header and Navigation Component
lisagjh/voorhoede pull request #8
Opened 2024-10-01 14:15 UTC by lisagjh

## What does this change?

Resolves [issue #18](https://github.com/fdnd-agency/voorhoede/issues/18)

Met deze pull request wil ik een header component toevoegen aan de main branch. De header bevat het DDA logo en het navigatie menu. Op een mobiel scherm (tot screen width 54rem of 864px) is dit menu ingeklapt en te openen met een button. Op een groter scherm staat de navigatie in de header.

## How Has This Been Tested?

- [x] Lighthouse test
- [x] W3C Validator 
- [x] Responsive Design test
- [x] Browser test

### Ligthouse

Alles is 100% !

<img width="549" alt="Scherm­afbeelding 2024-10-01 om 16 12 48" src="https://github.com/user-attachments/assets/1ad4934e-198d-4430-bb79-c3fa7455d6c3">

### W3C Validator

Geen errors gevonden.

<img width="1470" alt="Scherm­afbeelding 2024-10-01 om 16 13 11" src="https://github.com/user-attachments/assets/3d76b8a3-1bf8-4abe-a83a-10e02566f7b8">

## Images

#### FIGMA

Er is alleen een desktop design voor gemaakt, het mobiele design heb ik zelf tijdens het coderen gemaakt.

<img width="907" alt="Scherm­afbeelding 2024-10-01 om 16 09 16" src="https://github.com/user-attachments/assets/55c82c41-a747-467f-9238-e9061e234423">

#### MOBIEL

<img width="501" alt="Scherm­afbeelding 2024-10-01 om 16 10 32" src="https://github.com/user-attachments/assets/26c7c46d-ce87-44f1-afa0-85806ce63284">

#### DESKTOP

<img width="1075" alt="Scherm­afbeelding 2024-10-01 om 16 10 55" src="https://github.com/user-attachments/assets/6149a4f5-d8db-465c-8cfc-4fcd807be763">

## How to review

Je kan dit component testen op toegankelijkheid en functionaliteit. 
Sidenote hierbij is dat nog niet alle routes bestaan, dus niet alle opties zijn beschikbaar.

2024-10-01 15:06 UTC, yujing-student requested changes
Ik heb niet hetzelfde als wat jij hebt als ik op 1059px bij 754px schermbreedte heb

<img src="https://github.com/user-attachments/assets/94cdeb00-9b27-4dc0-a852-cb9edc1a5ade" width="1500px">

Deze if zorgt ervoor dat je menu pas geopend word als je op het hamburgermenu drukt

https://github.com/lisagjh/voorhoede/blob/50ee09977cd14d64c03e7453febb533547280f30/src/lib/Header.svelte#L42-L124


Als ik eerst het hamburger menu op mobiel open dan krijg ik hem ook op desktop te zien

![image](https://github.com/user-attachments/assets/0159bd26-c423-4181-b469-485fe16ced28)

<h1> de oplossing</h1>
Als je de if weg haalt je zou de interactie moeten werken.

````
  <nav
      class:show={isMenuOpen}
      aria-hidden={!isMenuOpen}
      in:slide={{ y: -100, duration: 300 }}
      out:slide={{ y: -100, duration: 300 }}
    >
      <ul>
        <li>
          <a href="/">Home</a>
        </li>
        <li>
          <a href="/over">Over ons</a>
        </li>
        <li>
          <a href="/events">Events</a>
        </li>
        <li>
          <a href="/publicaties">Publicaties</a>
        </li>
        <li>
          <a href="/leden">Leden</a>
        </li>
        <li>
          <a href="/vacatures">Vacatures</a>
        </li>
      </ul>

      <ul class="nav-cta">
        <li class="login">
          <a href="/#">
            Login
            <svg
              width="16"
              height="16"
              viewBox="0 0 16 16"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M8 3L13.0001 8.0001L8 13.0002"
                stroke="#364BF7"
                stroke-width="1.5"
                stroke-miterlimit="4.62023"
              />
              <path
                d="M3 8L13 8"
                stroke="#364BF7"
                stroke-width="1.5"
                stroke-miterlimit="4.62023"
                stroke-linejoin="round"
              />
            </svg>
          </a>
        </li>

        <li class="join">
          <a href="/#" class="join">Word lid</a>
          <svg
            width="16"
            height="16"
            viewBox="0 0 16 16"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M8 3L13.0001 8.0001L8 13.0002"
              stroke="#222226"
              stroke-width="1.5"
              stroke-miterlimit="4.62023"
            />
            <path
              d="M3 8L13 8"
              stroke="#222226"
              stroke-width="1.5"
              stroke-miterlimit="4.62023"
              stroke-linejoin="round"
            />
          </svg>
        </li>
      </ul>
    </nav>
````

2024-10-02 10:01 UTC, lisagjh commented
Na de vorige review heb ik de code aangepast.

# Changes
## Javascript

Je kan [hier](https://github.com/lisagjh/voorhoede/blob/405db0bbd3ff8bfad84202d5fcf6049dec0195e8/src/lib/Header.svelte#L1-L29) de JS bekijken.

Ik heb de code aangepast zodat het nu op groot scherm het menu automatisch opent, en de `aria-hidden` juist aanpast. Ik heb hiervoor een onMount gebruikt die de viewport width checkt, en een variabele update. In de code zelf staan meer comments met uitleg.

## HTML

Ik heb in de [HTML](https://github.com/lisagjh/voorhoede/blob/405db0bbd3ff8bfad84202d5fcf6049dec0195e8/src/lib/Header.svelte#L62-L65) een kleine aanpassing gedaan, zodat de nav de juiste variabele gebruikt.


# How has this been tested?

- [x] W3C validator
- [x] Lighthouse

## validator

Geen errors gevonden.

<img width="1415" alt="Scherm­afbeelding 2024-10-02 om 11 56 06" src="https://github.com/user-attachments/assets/c294700d-d372-4491-9b93-09464322732c">

## Lighthouse

De performance is nu 98 ipv 100, maar nog steeds groen.

<img width="503" alt="Scherm­afbeelding 2024-10-02 om 11 58 52" src="https://github.com/user-attachments/assets/189dd830-3b90-415f-85ca-a083d57dff1f">
<img width="483" alt="Scherm­afbeelding 2024-10-02 om 11 59 42" src="https://github.com/user-attachments/assets/e4cc7a0d-099c-4921-b124-244de55cca2b">

# How to review

Je kan dit component testen op responsiveness, toegankelijkheid en functionaliteit. Je kunt checken of de UI states genoeg feedback geven.
Ik hoor ook graag feedback op de inhoudelijke code, ik ben bang dat ik er veel te moeilijk over na zit te denken en dat het een stuk makkelijker kan.
_Sidenote hierbij is dat nog niet alle routes bestaan, dus niet alle opties zijn beschikbaar._

2024-10-02 10:45 UTC, Jason2426 commented
Overzichtelijke code inclusief duidelijke comments en een prima techniek uitgekozen voor het maken van het component.

2024-10-02 10:52 UTC, Jason2426 commented
Het logo van DDA is best klein gemaakt waarschijnlijk ivm ruimte voor de links en voor de toegankelijkheid (100%). Ik denk dat je de font size kan verkleinen of dan het logo iets groter maken. In het design zijn de links op desktop 12px's.

### Foto van branch
![image](https://github.com/user-attachments/assets/444cd32d-c136-433a-b97b-031d05e83dee)

### Referentie van Design
![image](https://github.com/user-attachments/assets/835313d8-e7c3-4b34-b6cb-eb3f286f3dc7)

2024-10-02 11:32 UTC, yujing-student approved these changes
De code ziet er overzichtelijk uit en de header werkt goed op desktop

2024-10-03 12:20 UTC, merged